/* Automatically generated by chibi-ffi; version: 0.5 */

#include <chibi/eval.h>

#include "imgui_src.h"
/*
types: (imgui_text_buffer ImVec2_t imgui_bool)
enums: ()
*/

sexp sexp_imgui_input_text_multiline_c_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1, sexp arg2, sexp arg3) {
  sexp res;
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  if (! (sexp_pointerp(arg1) && (sexp_pointer_tag(arg1) == sexp_unbox_fixnum(sexp_opcode_arg2_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg2_type(self)), arg1);
  if (! (sexp_pointerp(arg2) && (sexp_pointer_tag(arg2) == sexp_unbox_fixnum(sexp_opcode_arg3_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg3_type(self)), arg2);
  if (! sexp_exact_integerp(arg3))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg3);
  res = sexp_make_boolean(imgui_input_text_multiline_c(sexp_string_data(arg0), (struct imgui_text_buffer*)sexp_cpointer_value(arg1), *(struct ImVec2_t*)sexp_cpointer_value(arg2), sexp_sint_value(arg3)));
  return res;
}

sexp sexp_get_imgui_text_buffer_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  res = sexp_c_string(ctx, get_imgui_text_buffer((struct imgui_text_buffer*)sexp_cpointer_value(arg0)), -1);
  return res;
}

sexp sexp_set_imgui_text_buffer_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  if (! sexp_stringp(arg1))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg1);
  res = ((set_imgui_text_buffer((struct imgui_text_buffer*)sexp_cpointer_value(arg0), sexp_string_data(arg1))), SEXP_VOID);
  return res;
}

sexp sexp_init_imgui_text_buffer_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  if (! sexp_exact_integerp(arg1))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg1);
  res = ((init_imgui_text_buffer((struct imgui_text_buffer*)sexp_cpointer_value(arg0), sexp_sint_value(arg1))), SEXP_VOID);
  return res;
}

sexp sexp_imgui_end_group_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = ((ImGui_EndGroup()), SEXP_VOID);
  return res;
}

sexp sexp_imgui_begin_group_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = ((ImGui_BeginGroup()), SEXP_VOID);
  return res;
}

sexp sexp_imgui_get_text_line_height_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = sexp_make_flonum(ctx, ImGui_GetTextLineHeight());
  return res;
}

sexp sexp_imgui_get_frame_height_with_spacing_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = sexp_make_flonum(ctx, ImGui_GetFrameHeightWithSpacing());
  return res;
}

sexp sexp_imgui_end_child_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = ((ImGui_EndChild()), SEXP_VOID);
  return res;
}

sexp sexp_imgui_begin_child_c_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1, sexp arg2, sexp arg3) {
  sexp res;
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  if (! (sexp_pointerp(arg1) && (sexp_pointer_tag(arg1) == sexp_unbox_fixnum(sexp_opcode_arg2_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg2_type(self)), arg1);
  if (! sexp_exact_integerp(arg3))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg3);
  res = sexp_make_boolean(ImGui_BeginChild(sexp_string_data(arg0), *(struct ImVec2_t*)sexp_cpointer_value(arg1), sexp_truep(arg2), sexp_sint_value(arg3)));
  return res;
}

sexp sexp_imgui_same_line_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = ((ImGui_SameLine()), SEXP_VOID);
  return res;
}

sexp sexp_imgui_set_next_window_size_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  if (! sexp_exact_integerp(arg1))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg1);
  res = ((ImGui_SetNextWindowSize(*(struct ImVec2_t*)sexp_cpointer_value(arg0), sexp_sint_value(arg1))), SEXP_VOID);
  return res;
}

sexp sexp_imgui_button_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  res = sexp_make_boolean(ImGui_Button(sexp_string_data(arg0)));
  return res;
}

sexp sexp_imgui_end_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = ((ImGui_End()), SEXP_VOID);
  return res;
}

sexp sexp_imgui_begin2_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1, sexp arg2) {
  sexp res;
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  if (! (sexp_pointerp(arg1) && (sexp_pointer_tag(arg1) == sexp_unbox_fixnum(sexp_opcode_arg2_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg2_type(self)), arg1);
  if (! sexp_exact_integerp(arg2))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg2);
  res = sexp_make_boolean(imgui_begin2(sexp_string_data(arg0), (struct imgui_bool*)sexp_cpointer_value(arg1), sexp_sint_value(arg2)));
  return res;
}

sexp sexp_imgui_begin1_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1) {
  sexp res;
  if (! sexp_stringp(arg0))
    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);
  if (! sexp_exact_integerp(arg1))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg1);
  res = sexp_make_boolean(imgui_begin1(sexp_string_data(arg0), sexp_sint_value(arg1)));
  return res;
}

sexp sexp_is_android_p_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = sexp_make_boolean(is_android());
  return res;
}

sexp sexp_use_bool_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  res = ((use_bool((struct imgui_bool*)sexp_cpointer_value(arg0))), SEXP_VOID);
  return res;
}

sexp sexp_make_imgui_text_buffer_stub (sexp ctx, sexp self, sexp_sint_t n) {
  struct imgui_text_buffer* r;
  sexp_gc_var1(res);
  sexp_gc_preserve1(ctx, res);
  res = sexp_alloc_tagged(ctx, sexp_sizeof(cpointer), sexp_unbox_fixnum(sexp_opcode_return_type(self)));
  sexp_cpointer_value(res) = calloc(1, sizeof(struct imgui_text_buffer));
  r = (struct imgui_text_buffer*) sexp_cpointer_value(res);
  memset(r, 0, sizeof(struct imgui_text_buffer));
  sexp_freep(res) = 1;
  sexp_gc_release1(ctx);
  return res;
}

sexp sexp_imgui_text_buffer_get_maxlen (sexp ctx, sexp self, sexp_sint_t n, sexp x) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  return sexp_make_integer(ctx, ((struct imgui_text_buffer*)sexp_cpointer_value(x))->maxlen);
}

sexp sexp_imgui_text_buffer_set_maxlen (sexp ctx, sexp self, sexp_sint_t n, sexp x, sexp v) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  if (! sexp_exact_integerp(v))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, v);
  ((struct imgui_text_buffer*)sexp_cpointer_value(x))->maxlen = sexp_sint_value(v);
  return SEXP_VOID;
}

sexp sexp_make_imgui_imvec2_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1) {
  struct ImVec2_t* r;
  sexp_gc_var1(res);
  sexp_gc_preserve1(ctx, res);
  res = sexp_alloc_tagged(ctx, sexp_sizeof(cpointer), sexp_unbox_fixnum(sexp_opcode_return_type(self)));
  sexp_cpointer_value(res) = calloc(1, sizeof(struct ImVec2_t));
  r = (struct ImVec2_t*) sexp_cpointer_value(res);
  memset(r, 0, sizeof(struct ImVec2_t));
  sexp_freep(res) = 1;
  ((struct ImVec2_t*)sexp_cpointer_value(res))->x = sexp_flonum_value(arg0);
  ((struct ImVec2_t*)sexp_cpointer_value(res))->y = sexp_flonum_value(arg1);
  sexp_gc_release1(ctx);
  return res;
}

sexp sexp_ImVec2_t_get_x (sexp ctx, sexp self, sexp_sint_t n, sexp x) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  return sexp_make_flonum(ctx, ((struct ImVec2_t*)sexp_cpointer_value(x))->x);
}

sexp sexp_ImVec2_t_set_x (sexp ctx, sexp self, sexp_sint_t n, sexp x, sexp v) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  if (! sexp_flonump(v))
    return sexp_type_exception(ctx, self, SEXP_FLONUM, v);
  ((struct ImVec2_t*)sexp_cpointer_value(x))->x = sexp_flonum_value(v);
  return SEXP_VOID;
}

sexp sexp_ImVec2_t_get_y (sexp ctx, sexp self, sexp_sint_t n, sexp x) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  return sexp_make_flonum(ctx, ((struct ImVec2_t*)sexp_cpointer_value(x))->y);
}

sexp sexp_ImVec2_t_set_y (sexp ctx, sexp self, sexp_sint_t n, sexp x, sexp v) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  if (! sexp_flonump(v))
    return sexp_type_exception(ctx, self, SEXP_FLONUM, v);
  ((struct ImVec2_t*)sexp_cpointer_value(x))->y = sexp_flonum_value(v);
  return SEXP_VOID;
}

sexp sexp_make_imgui_bool_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  struct imgui_bool* r;
  sexp_gc_var1(res);
  sexp_gc_preserve1(ctx, res);
  res = sexp_alloc_tagged(ctx, sexp_sizeof(cpointer), sexp_unbox_fixnum(sexp_opcode_return_type(self)));
  sexp_cpointer_value(res) = calloc(1, sizeof(struct imgui_bool));
  r = (struct imgui_bool*) sexp_cpointer_value(res);
  memset(r, 0, sizeof(struct imgui_bool));
  sexp_freep(res) = 1;
  ((struct imgui_bool*)sexp_cpointer_value(res))->the_bool = sexp_truep(arg0);
  sexp_gc_release1(ctx);
  return res;
}

sexp sexp_imgui_bool_get_the_bool (sexp ctx, sexp self, sexp_sint_t n, sexp x) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  return sexp_make_boolean(((struct imgui_bool*)sexp_cpointer_value(x))->the_bool);
}

sexp sexp_imgui_bool_set_the_bool (sexp ctx, sexp self, sexp_sint_t n, sexp x, sexp v) {
  if (! (sexp_pointerp(x) && (sexp_pointer_tag(x) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), x);
  ((struct imgui_bool*)sexp_cpointer_value(x))->the_bool = sexp_truep(v);
  return SEXP_VOID;
}


sexp sexp_init_library (sexp ctx, sexp self, sexp_sint_t n, sexp env, const char* version, const sexp_abi_identifier_t abi) {
  sexp sexp_imgui_text_buffer_type_obj;
  sexp sexp_ImVec2_t_type_obj;
  sexp sexp_imgui_bool_type_obj;
  sexp_gc_var3(name, tmp, op);
  if (!(sexp_version_compatible(ctx, version, sexp_version)
        && sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return SEXP_ABI_ERROR;
  sexp_gc_preserve3(ctx, name, tmp, op);
  name = sexp_intern(ctx, "imgui-flags/read-only", 21);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, ImGuiInputTextFlags_ReadOnly));
  name = sexp_intern(ctx, "imgui-flags/allow-tab-input", 27);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, ImGuiInputTextFlags_AllowTabInput));
  name = sexp_intern(ctx, "imgui-flags/once", 16);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, ImGuiCond_Once));
  name = sexp_intern(ctx, "imgui-flags/no-collapse", 23);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, ImGuiWindowFlags_NoCollapse));
  name = sexp_c_string(ctx, "imgui_text_buffer", -1);
  sexp_imgui_text_buffer_type_obj = sexp_register_c_type(ctx, name, sexp_finalize_c_type);
  tmp = sexp_string_to_symbol(ctx, name);
  sexp_env_define(ctx, env, tmp, sexp_imgui_text_buffer_type_obj);
  sexp_type_slots(sexp_imgui_text_buffer_type_obj) = SEXP_NULL;
  sexp_push(ctx, sexp_type_slots(sexp_imgui_text_buffer_type_obj), sexp_intern(ctx, "maxlen", -1));
  sexp_type_getters(sexp_imgui_text_buffer_type_obj) = sexp_make_vector(ctx, SEXP_ONE, SEXP_FALSE);
  sexp_type_setters(sexp_imgui_text_buffer_type_obj) = sexp_make_vector(ctx, SEXP_ONE, SEXP_FALSE);
  name = sexp_c_string(ctx, "ImVec2_t", -1);
  sexp_ImVec2_t_type_obj = sexp_register_c_type(ctx, name, sexp_finalize_c_type);
  tmp = sexp_string_to_symbol(ctx, name);
  sexp_env_define(ctx, env, tmp, sexp_ImVec2_t_type_obj);
  sexp_type_slots(sexp_ImVec2_t_type_obj) = SEXP_NULL;
  sexp_push(ctx, sexp_type_slots(sexp_ImVec2_t_type_obj), sexp_intern(ctx, "y", -1));
  sexp_push(ctx, sexp_type_slots(sexp_ImVec2_t_type_obj), sexp_intern(ctx, "x", -1));
  sexp_type_getters(sexp_ImVec2_t_type_obj) = sexp_make_vector(ctx, SEXP_TWO, SEXP_FALSE);
  sexp_type_setters(sexp_ImVec2_t_type_obj) = sexp_make_vector(ctx, SEXP_TWO, SEXP_FALSE);
  name = sexp_c_string(ctx, "imgui_bool", -1);
  sexp_imgui_bool_type_obj = sexp_register_c_type(ctx, name, sexp_finalize_c_type);
  tmp = sexp_string_to_symbol(ctx, name);
  sexp_env_define(ctx, env, tmp, sexp_imgui_bool_type_obj);
  sexp_type_slots(sexp_imgui_bool_type_obj) = SEXP_NULL;
  sexp_push(ctx, sexp_type_slots(sexp_imgui_bool_type_obj), sexp_intern(ctx, "the_bool", -1));
  sexp_type_getters(sexp_imgui_bool_type_obj) = sexp_make_vector(ctx, SEXP_ONE, SEXP_FALSE);
  sexp_type_setters(sexp_imgui_bool_type_obj) = sexp_make_vector(ctx, SEXP_ONE, SEXP_FALSE);
  op = sexp_define_foreign(ctx, env, "imgui-bool-set", 2, (sexp_proc1)sexp_imgui_bool_set_the_bool);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_bool_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
  }
  if (sexp_vectorp(sexp_type_setters(sexp_imgui_bool_type_obj))) sexp_vector_set(sexp_type_setters(sexp_imgui_bool_type_obj), SEXP_ZERO, op);
  op = sexp_define_foreign(ctx, env, "imgui-bool-get", 1, (sexp_proc1)sexp_imgui_bool_get_the_bool);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_bool_type_obj));
  }
  if (sexp_vectorp(sexp_type_getters(sexp_imgui_bool_type_obj))) sexp_vector_set(sexp_type_getters(sexp_imgui_bool_type_obj), SEXP_ZERO, op);
  op = sexp_define_foreign(ctx, env, "make-imgui-bool", 1, (sexp_proc1)sexp_make_imgui_bool_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_bool_type_obj));
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
  }
  op = sexp_define_foreign(ctx, env, "imgui-imvec2-y-set", 2, (sexp_proc1)sexp_ImVec2_t_set_y);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FLONUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FLONUM);
  }
  if (sexp_vectorp(sexp_type_setters(sexp_ImVec2_t_type_obj))) sexp_vector_set(sexp_type_setters(sexp_ImVec2_t_type_obj), SEXP_ONE, op);
  op = sexp_define_foreign(ctx, env, "imgui-imvec2-y-get", 1, (sexp_proc1)sexp_ImVec2_t_get_y);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FLONUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
  }
  if (sexp_vectorp(sexp_type_getters(sexp_ImVec2_t_type_obj))) sexp_vector_set(sexp_type_getters(sexp_ImVec2_t_type_obj), SEXP_ONE, op);
  op = sexp_define_foreign(ctx, env, "imgui-imvec2-x-set", 2, (sexp_proc1)sexp_ImVec2_t_set_x);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FLONUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FLONUM);
  }
  if (sexp_vectorp(sexp_type_setters(sexp_ImVec2_t_type_obj))) sexp_vector_set(sexp_type_setters(sexp_ImVec2_t_type_obj), SEXP_ZERO, op);
  op = sexp_define_foreign(ctx, env, "imgui-imvec2-x-get", 1, (sexp_proc1)sexp_ImVec2_t_get_x);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FLONUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
  }
  if (sexp_vectorp(sexp_type_getters(sexp_ImVec2_t_type_obj))) sexp_vector_set(sexp_type_getters(sexp_ImVec2_t_type_obj), SEXP_ZERO, op);
  op = sexp_define_foreign(ctx, env, "make-imgui-imvec2", 2, (sexp_proc1)sexp_make_imgui_imvec2_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_FLONUM);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FLONUM);
  }
  op = sexp_define_foreign(ctx, env, "imgui-text-buffer-maxlen-set", 2, (sexp_proc1)sexp_imgui_text_buffer_set_maxlen);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
  }
  if (sexp_vectorp(sexp_type_setters(sexp_imgui_text_buffer_type_obj))) sexp_vector_set(sexp_type_setters(sexp_imgui_text_buffer_type_obj), SEXP_ZERO, op);
  op = sexp_define_foreign(ctx, env, "imgui-text-buffer-maxlen-get", 1, (sexp_proc1)sexp_imgui_text_buffer_get_maxlen);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
  }
  if (sexp_vectorp(sexp_type_getters(sexp_imgui_text_buffer_type_obj))) sexp_vector_set(sexp_type_getters(sexp_imgui_text_buffer_type_obj), SEXP_ZERO, op);
  op = sexp_define_foreign(ctx, env, "make-imgui_text_buffer", 0, (sexp_proc1)sexp_make_imgui_text_buffer_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
  }
  op = sexp_define_foreign(ctx, env, "imgui-input-text-multiline-c", 4, (sexp_proc1)sexp_imgui_input_text_multiline_c_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
    sexp_opcode_arg3_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
    sexp_opcode_argn_type(op) = sexp_make_vector(ctx, SEXP_ONE, sexp_make_fixnum(SEXP_OBJECT));
    sexp_vector_set(sexp_opcode_argn_type(op), SEXP_ZERO, sexp_make_fixnum(SEXP_FIXNUM));
  }
  op = sexp_define_foreign(ctx, env, "get-imgui-text-buffer", 1, (sexp_proc1)sexp_get_imgui_text_buffer_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_STRING);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
  }
  op = sexp_define_foreign(ctx, env, "set-imgui-text-buffer", 2, (sexp_proc1)sexp_set_imgui_text_buffer_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_STRING);
  }
  op = sexp_define_foreign(ctx, env, "init_imgui_text_buffer", 2, (sexp_proc1)sexp_init_imgui_text_buffer_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_text_buffer_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
  }
  op = sexp_define_foreign(ctx, env, "imgui-end-group", 0, (sexp_proc1)sexp_imgui_end_group_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
  }
  op = sexp_define_foreign(ctx, env, "imgui-begin-group", 0, (sexp_proc1)sexp_imgui_begin_group_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
  }
  op = sexp_define_foreign(ctx, env, "imgui-get-text-line-height", 0, (sexp_proc1)sexp_imgui_get_text_line_height_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FLONUM);
  }
  op = sexp_define_foreign(ctx, env, "imgui-get-frame-height-with-spacing", 0, (sexp_proc1)sexp_imgui_get_frame_height_with_spacing_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FLONUM);
  }
  op = sexp_define_foreign(ctx, env, "imgui-end-child", 0, (sexp_proc1)sexp_imgui_end_child_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
  }
  op = sexp_define_foreign(ctx, env, "imgui-begin-child-c", 4, (sexp_proc1)sexp_imgui_begin_child_c_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
    sexp_opcode_arg3_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_argn_type(op) = sexp_make_vector(ctx, SEXP_ONE, sexp_make_fixnum(SEXP_OBJECT));
    sexp_vector_set(sexp_opcode_argn_type(op), SEXP_ZERO, sexp_make_fixnum(SEXP_FIXNUM));
  }
  op = sexp_define_foreign(ctx, env, "imgui-same-line", 0, (sexp_proc1)sexp_imgui_same_line_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
  }
  op = sexp_define_foreign(ctx, env, "imgui-set-next-window-size", 2, (sexp_proc1)sexp_imgui_set_next_window_size_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_ImVec2_t_type_obj));
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
  }
  op = sexp_define_foreign(ctx, env, "imgui-button", 1, (sexp_proc1)sexp_imgui_button_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
  }
  op = sexp_define_foreign(ctx, env, "imgui-end", 0, (sexp_proc1)sexp_imgui_end_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
  }
  op = sexp_define_foreign(ctx, env, "imgui-begin2", 3, (sexp_proc1)sexp_imgui_begin2_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_bool_type_obj));
    sexp_opcode_arg3_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
  }
  op = sexp_define_foreign(ctx, env, "imgui-begin1", 2, (sexp_proc1)sexp_imgui_begin1_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
  }
  op = sexp_define_foreign(ctx, env, "is-android?", 0, (sexp_proc1)sexp_is_android_p_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_BOOLEAN);
  }
  op = sexp_define_foreign(ctx, env, "use_bool", 1, (sexp_proc1)sexp_use_bool_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = SEXP_VOID;
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(sexp_type_tag(sexp_imgui_bool_type_obj));
  }
  sexp_gc_release3(ctx);
  return SEXP_VOID;
}

